// The Daily Charlatan — the ten most recent posts from Ali's first blog
// (thedailycharlatan.godaddysites.com), recovered whole.

import type { Essay } from "./writing";

export const charlatanEssays: Essay[] = [
  {
    "slug": "accept-your-experiences",
    "title": "Accept Your Experiences",
    "subtitle": "The stolen bike that made Muhammad Ali a boxer.",
    "date": "April 24, 2024",
    "paragraphs": [
      "At 12 years old, Cassius Clay bought his first bicycle for $60.",
      "After hearing about the town fair in downtown Louisville, he decided to take his new gift for a ride and see the event.",
      "When the show was over, Cassius came out and found his prized vehicle was gone.",
      "He scrambled to find police officer Joe Martin and told him, through tears, that “if I find the kid who stole my bike, I’ll whup him.”",
      "Martin told Cassius he’d better learn how to box before seeking out a fight and offered the kid to join the classes he ran.",
      "Clay accepted, and became Muhammad Ali.",
      "Cassius Clay, 12 years old & Muhammad Ali, 21 years old (right)",
      "His journey to becoming among the most significant sports figures of the 20th century can be traced back to this single day.",
      "This is a great example of the butterfly effect, the idea that the world is deeply interconnected, such that one small occurrence can influence a much larger complex system.",
      "We can look back now with admiration and think “Damn, it’s cool how that interaction led to so much.”",
      "But during the actual experience, Ali wasn’t predicting the beautiful journey to come.",
      "He was pissed off thinking about beating up the motherfucker who stole his bike.",
      "Similarly, we encounter circumstances that don’t fit into our perception of what reality should be and often have natural reactions of distaste, boredom, or anger.",
      "Trivial happenings like taking a wrong turn on the highway, being in a group project with people you don’t know, having to buy milk from the store at a certain time, these potentially annoying events hold hidden significance.",
      "Maybe taking the wrong turn saves you from dying in a crash.",
      "Maybe you meet your lover through the group project.",
      "Maybe going to that store at that time means you see video-cameras on sale, and you think “why not?” This marks the beginning of a film career.",
      "Or maybe none of that’s true and you just carry on living.",
      "But those little moments are woven into your story, and all the great things you find couldn’t have happened without them.",
      "Another example of this phenomenon:",
      "For you to live, your parents had to meet.",
      "Your 4 grandparents had to meet.",
      "Your 8 great-grandparents had to meet.",
      "Your 16 great-great-grandparents had to meet.",
      "Your 32 great-great-great-grandparents had to meet.",
      "All the painful, annoying, random, insignificant moments that led them to live and cross paths with one another led to your existence and exploration of the world. If things were a little different, you’d never be here.",
      "Everything that happens to you is part of a larger story. Some of it might suck, but if you open your heart, it can lead you to amazing paths. Trust that the whims of fate all play into a greater good.",
      "You might get your bicycle stolen. Later, you might become the greatest heavyweight boxing champion of all time.",
      "Don’t reject your experiences. You don’t know where they’ll take you.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024",
      "What Are Friends For?",
      "Feb 18, 2024"
    ]
  },
  {
    "slug": "how-to-practice-antifragility",
    "title": "How to Practice Antifragility",
    "subtitle": "How to grow from the things that hurt you.",
    "date": "April 24, 2024",
    "paragraphs": [
      "One of the most rewarding traits we can build within ourselves is antifragility.",
      "Antifragility is the property of something getting stronger and thriving as a result of stress, mistakes, failure, or disorder.",
      "It surpasses resilience as, rather than simply being able to endure hardship, antifragility actively finds ways to grow from it.",
      "Living through this lens is a stronger model for happiness since it bases our confidence and well-being on the way we handle situations rather than the situations themselves.",
      "Our minds are much better suited for life’s inevitable shitshows when we’re expecting them and already looking for ways to make light of them.",
      "Seeing the world this way doesn’t come naturally to everyone. Fortunately, antifragility can be developed much like any other skill.",
      "There are many ways to grow this muscle, but I like to simplify it into a single question.",
      "Whenever you find yourself in trouble, ask the question:",
      "“How is this the best thing that’s ever happened to me?”",
      "It makes no sense, especially when asked in more painful times, but it trains your mind to reframe negative circumstances into opportunities to grow.",
      "Here’s an example:",
      "I’ve been fired from the job I’ve had for 5 years.",
      "This causes uncertainty, doubt, and stress to affect my head. I hear thoughts of “Fuck. What do I do? I’m cooked. Life sucks.”",
      "Then I ask myself,",
      "How is this the best thing that’s ever happened to me?",
      "And I push myself to come up with reasons.",
      "Well, I probably wouldn’t have left my job anytime soon if I hadn’t been fired, meaning I’d continue living the same routine for another 5 years. Now, I’m forced to have new experiences and try a new path, at least for a while.",
      "This is just another part of my story, and is possibly the spark for a new chapter of my life.",
      "Even if nothing crazy comes out of this and I just get another job, I’ll have more trust in myself to deal with anything that comes my way, since I’ve already made it through being fired.",
      "And just like that, an existential crisis is transformed into an opportunity for growth.",
      "By asking ourselves the right questions, we can practice finding ways to thrive in any circumstance, be it a delayed flight, messing up a presentation, a bad breakup, or burnt toast, until antifragility becomes second nature.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024",
      "What Are Friends For?",
      "Feb 18, 2024"
    ]
  },
  {
    "slug": "big-dreams-small-steps",
    "title": "Big Dreams, Small Steps",
    "subtitle": "Big dreams are just small steps brought together.",
    "date": "February 26, 2024",
    "paragraphs": [
      "“Great things are not done by impulse, but by a series of small things brought together.” -Vincent Van Gogh",
      "The bigger the dream, the harder it is to think about. When our ambitions are complex and require a large body of work to accomplish, it’s easy to get discouraged and give up prematurely, or worse, not even allow ourselves to entertain the dreams.",
      "It’s quite tragic to hear people in conversation mention something they want to do, then quickly dismiss the idea that they could ever do it.",
      "In many cases, this lack of confidence doesn’t come from a lack of ability to meet a challenge, but rather a misinterpretation of how big the challenge actually is.",
      "Perceiving our dream as One Big Task can be incredibly limiting, because it feels like we need to perform an enormous jump from Here to There, instantaneously creating a new life.",
      "It makes sense that so many dreams never become reality, because in our minds, they seem like these enormous individual efforts that none of us would feel ready for.",
      "Fortunately, Impossible Dreams are not the product of an Impossible Step, but rather a large collection of extremely possible little steps which accumulate over time to form something larger.",
      "“The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and starting on the first one.” -Mark Twain",
      "This website was a product of that exact process. After I watched The French Dispatch, a movie featuring a beautiful magazine, I thought, “Damn, it’d be pretty cool if I could make a magazine featuring all the beautiful things I find.”",
      "But I had no idea how to make it happen.",
      "And so I sat in French class for the next month thinking about it, dreaming. That was when I came up with the name The Daily Charlatan.",
      "After having these ideas for what I wanted it to look like, how I could interview people, have artists submit their work, have a music section, a science-based happiness section, have short stories, jokes, so many ideas, I got tired of carrying them around in my head.",
      "Then I asked myself, if making and organizing a physical magazine is too complex and unclear (for me), what can I do now to at least move toward something called The Daily Charlatan?",
      "And I thought, websites might be easier to set up.",
      "So at like 10:17pm on a Sunday, I went to my computer, searched up “How To Make a Website”, and made one called thedailycharlatan. Then I closed my computer and went to sleep. Nothing else.",
      "The next day, I chose the pictures to decorate the site.",
      "The next day, I chose an idea to write about.",
      "The next day, I wrote a paragraph of it.",
      "The next day, I finished the article, and posted it.",
      "The next day, I chose an idea to write about.",
      "And so on.",
      "I’ve been writing here ever since, and now something I was daydreaming about in French class exists in reality.",
      "It’s made my life sweeter, it’s given me joy and love for creating and sharing with others, and I hope to apply this same way of thinking toward all the other things I dream about.",
      "I hope you do, too.",
      "Bring what you dream about into the world and share it.",
      "Take your huge, cloudy goal, the one you’d never be able to reach from where you are, and cut it in half, then again, then again and again until you find the smallest and most immediate milestone you can reach from where you are.",
      "Where do you want to be in a year?",
      "Knowing that, where do you want to be in 6 months?",
      "In 3 months?",
      "In 1 month?",
      "In 2 weeks?",
      "In 1 week?",
      "Tomorrow?",
      "In an hour?",
      "What can you do right now?",
      "Alright, go do that.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "What Are Friends For?",
      "Feb 18, 2024"
    ]
  },
  {
    "slug": "what-are-friends-for",
    "title": "What Are Friends For?",
    "subtitle": "On the deeper treasures of friendship.",
    "date": "February 18, 2024",
    "paragraphs": [
      "\"We were together. I forget the rest.\" -Walt Whitman",
      "At the most basic level, we turn to friends when solitude becomes too unpleasant to bear.",
      "A cup of tea and amusing conversation with the homies wipes away the chaos that enters our minds when left to our own devices.",
      "But simple amusement only scratches the surface of what friendship can do for us.",
      "There are deeper treasures in friends which often go undiscovered, either because we have no idea they exist, or because we are too scared to dig them up.",
      "Yet the curious and courageous souls still ask:",
      "How can we find these deeper joys of friendship?",
      "Short Answer:",
      "The deeper treasures of friendship are uncovered when the homies can be vulnerable and accept one another’s struggles, while picking each other up and striving for growth, together.",
      "Long Answer:",
      "1) Vulnerability",
      "“The fun is having friends who help each other get free.” -Ram Dass",
      "While navigating day-to-day life, humans shapeshift to better fit social situations.",
      "For instance, when the Starbucks barista asks me How I’m Doing Today, I say “I’m doing well, it’s a beautiful day.” rather than saying “I’m worried that I’ll never measure up to my parents expectations.”",
      "Although both might be true, the first answer is much easier to manage in conversation.",
      "In order to keep things smooth, we restrict the parts of ourselves that are too complex, disturbing, and passionate for others to deal with. But this gets quite uncomfortable over extended periods of time.",
      "Me, at Starbucks.",
      "The greatest friendships serve as an oasis from these restrictions, where pretending is no longer necessary, where we are allowed to be without picking and choosing what parts of us to be.",
      "Good Homies give you the treasure of freedom, inviting you to lay out the most incomprehensible, goofy, strange, childish sides of yourself.",
      "And even if they don’t understand all of it, they accept all of it.",
      "It’s a wonderful gift, but it does not come easily. The cost of freedom is vulnerability.",
      "Oftentimes, it’s difficult to fully express oneself, even around friends. When you’re hurting, the basic instinct might be to hide it because you don't want to look like a bitch, or it’s not normal for the group to address negativity together.",
      "The same applies to positive emotions as well.",
      "You might avoid telling your friends you’re proud of them and appreciate them and love them, because it’s not “normal” to do this. You don’t want to weird the bros out.",
      "But in trying so hard to appear “normal,” all we’re doing is robbing ourselves!",
      "In tough times, expressing our troubles to friends opens us up to the healing nature of community. To feel seen and heard, to know that someone cares, these gifts tremendously lighten the weight of the world.",
      "And in wonderful times, our fear of being weird stops us from exclaiming and loving life and each other out loud. Why would you ever hold back? How are your friends to know how much they mean to you if you never tell them?",
      "When you carry the world’s intrusive expectation into the sacred grounds of friendship, pretending to be “fine and normal” all the time, you are building connections based on dishonest performance.",
      "When you allow yourself to be vulnerable, presenting yourself just as you are, you are building friendships on a foundation of truth.",
      "And the truth shall set you free.",
      "2) Collective Growth",
      "“Each friend represents a world in us, a world possibly not born until they arrive, and it is only by this meeting that a new world is born.” ― Anais Nin",
      "It’s a pleasant opportunity to escape boredom by joking around and relaxing with homies. And indeed, one of the greatest joys of love is simply passing the time together.",
      "But it’s quite possible to mess around and have fun with most people. What distinguishes great friendships is that, in addition to having fun, the connection leads to collective growth.",
      "After hanging out together, you influence one another positively, bringing each other closer to the people you want to be.",
      "Hanging around kind people, you get a little kinder, because you’re defaulting to the norms of those you spend time with.",
      "Hanging around ambitious people, their excitement rubs off on you, and you can turn to them for advice and encouragement.",
      "Hanging around athletic people, your activities might be to play sports or go to the gym together, joking between workouts and running together.",
      "Hanging around creative people, you might be pushed to see the world in a more interesting way, and perhaps might even try new artistic endeavors.",
      "Great friends are those who challenge you, who push you to move toward the person you want to be, and who say “what the fuck?” when you’re not.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  },
  {
    "slug": "bounce-back",
    "title": "Bounce Back",
    "subtitle": "On getting back up quicker.",
    "date": "February 10, 2024",
    "paragraphs": [
      "Bruce Lee",
      "“But we cannot simply sit and stare at our wounds forever.”",
      "-Haruki Murakami",
      "In a period of fatigue, anger, or hopelessness, it’s easy to keep ourselves in that state longer than necessary.",
      "I feel tired, so I’m gonna lay down and scroll.",
      "I feel sad, so I’m gonna listen to melancholy music and eat barbecue chips.",
      "I feel mad, so I’m gonna sit here and think about how mad I am.",
      "At some point, the natural response is gone and you’re just doing it to yourself.",
      "In order to prevent this, there are two questions I ask myself:",
      "1) “How can I bounce back as fast as possible?”",
      "Making the clear intention to get yourself out of a rut is extremely helpful, as your thoughts start to revolve around that goal.",
      "The negative thoughts surrounding your situation sound less and less like the truth, and you can reconstruct your thinking to be empowering and helpful.",
      "2) What can I do right now that will give me more energy?",
      "Taking small, immediate steps is very important to get the ball rolling again.",
      "Usually, when I feel extremely tired or demotivated, I feel like taking a 3 hour nap or watching a movie. But I know these options won’t leave me feeling much better afterward.",
      "So after asking myself what I can do for energy, I usually find myself taking a walk, exercising, drinking coffee with my mom, cleaning my room, or taking a shower.",
      "These light activities give me a small sense of fulfillment and motivation which makes it easier to take on harder things like studying, writing, running, or working on a business.",
      "The point of these two questions is to push myself to take charge of my situation and figure out what small steps I can take to energize myself. Ultimately, it’s in our hands to help ourselves. Life will hit us hard, get us tired, sad, apathetic, pissed, bored. But we decide how long we’ll stay down.",
      "How fast can you bounce back?",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  },
  {
    "slug": "enjoying-goals",
    "title": "Enjoying Goals",
    "subtitle": "You don't have to choose between enjoying life and improving it.",
    "date": "February 4, 2024",
    "paragraphs": [
      "At first glance, it might seem that striving toward goals and appreciating life for what it is are two opposing processes. Goals push us to think of the future, while appreciation requires us to think in the present.",
      "Thus, it often feels like we need to choose between enjoying life and improving it.",
      "But this doesn’t have to be the case.",
      "In fact, goals can serve as tools that help us experience a greater sense of meaning, interest, and fun on a daily basis.",
      "Imagine a group of kids kicking a soccer ball around the neighborhood. Depending on how skilled they are, this can be quite an enjoyable, stressless activity. After a while, however, it starts to feel boring and meaningless.",
      "Their movements aren’t really adding up to anything interesting, so they decide to make teams and set up goals with their backpacks.",
      "With something to strive for, the runs and kicks become part of a larger story, creating excitement within the kids which pushes them to run faster and actually care about what they’re doing.",
      "They’re given a game to play.",
      "This process can be recreated in any aspect of our lives. Goals organize our daily efforts and weave them together into an interesting story, giving us more energy, confidence, and interest in our days.",
      "To fully enjoy the benefits of having goals, however, we must be aware of the danger in placing excessive importance on reaching them.",
      "Revisiting the soccer game, if a kid used “winning” as the sole measure of his happiness, he’d be choosing to enjoy the game only on occasional moments of success. If his team lost or was struggling, the game might become a source of hate or distress, becoming more harmful than interesting.",
      "On the other hand, the kid who tries to play her best while appreciating the game regardless of outcome is more likely to have fun and grow through the experience. She’s also more likely to win, too, as she’s driven by a love of the activity rather than outcomes.",
      "There are two ingredients to maximize the benefit of goals:",
      "1. Try your best to reach the goal.",
      "2. Find your joy in the pursuit rather than the outcome.",
      "With this mindset, striving for growth and enjoying the present merge together. Our objectives become the guiding force of our daily activities, giving us greater opportunity to have fun, to push ourselves, and to take an active role in life.",
      "Goals give us a game to play. And who knows? If you play long enough, you might score a few.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  },
  {
    "slug": "the-cost-of-knowing",
    "title": "The Cost of Knowing",
    "subtitle": "On choosing without all the information.",
    "date": "January 18, 2024",
    "paragraphs": [
      "I visited a foreign country last summer by train, so foreign that I hadn’t heard of any foods the train’s kitchen offered for meals.",
      "At lunch, the server-lady offered me a choice between pide and gözleme, which felt paralyzing for a moment.",
      "Pide",
      "Gözleme",
      "I had no clue what they tasted like. Naturally, I didn’t want to choose the wrong one because I would have wasted an opportunity to eat the right one.",
      "But I didn’t KNOW which one was the right one.",
      "At this point, you might be thinking, “Damn, it doesn’t fucking matter if you ate pide or gözleme. Nobody cares.”",
      "But this exciting story can actually portray the fear of regret, and how it hurts our ability to make and accept choices.",
      "When confronted with important decisions, there is a combination of two things which stop us from moving forward:",
      "Not knowing which choice will make us happy",
      "Being scared of making the “unhappy choice” and wasting time where we could’ve been happy",
      "And so we stay in limbo, torn between pide and gözleme.",
      "How do we reconcile this problem?",
      "Short Answer: Just choose something. It gives you experience and knowledge of what you like and don’t like.",
      "Long Answer:",
      "You must understand that nobody is born knowing what they like or want or what makes them happy.",
      "There are some lucky nerds who say they want to be a doctor at 5 years old and at 40 when they’re a doctor they think, “Damn yeah I really like this shit.”",
      "But for most people, they learn what they want through trying and investing in a lot of different things, some of which end up sucking, and this gives them an understanding of what makes them happy and what doesn't.",
      "The cost of knowing is time.",
      "If you have two options, and you don’t have a strong idea of which one you prefer, then you invest time following one choice until you can comfortably say which one is right or wrong for you.",
      "Stay at your job or try something new?",
      "Stay at your job a while more till you realize it REALLY sucks and you can leave confidently or till you find out it gets better and you just needed more training.",
      "Try something new till you find out you prefer your previous job or till you see that this is what you were meant to do with your life.",
      "Marry my partner?",
      "Continue dating until you move closer and closer to a definitive yes or no.",
      "Should I major in this?",
      "If you have a decent interest, try it out (either as an area of study in college or experimenting/studying on your own for free) till you notice yourself growing happier through the study or getting bored.",
      "Should I watch Breaking Bad or The Office?",
      "Breaking Bad",
      "I’m kidding, watch one of them till you realize you love it or want to switch. They’re both good.",
      "I will say there are two caveats to keep in mind, however.",
      "When making choices to see if it feels better or worse after time, I’d advise to choose the option that’s easiest to undo. If you’re in medicine and think you might be interested in a different field, you don’t have to blow another 100k getting a degree in it. You can start small. In the marriage example above, you could keep dating to see if you want to marry them, or you could marry them and see if it works out. But divorce is harder than simply breaking up. And it’s hard to get a job back after quitting it. If unsure, choose the easiest option to undo, and go from there.",
      "If you DO clearly know what makes you happy and what doesn’t from your options, it doesn’t pay much to continue trying what doesn’t make you happy. That IS wasted time. The advice of paying time applies when you DON’T know what you want.",
      "What should I do?",
      "Time is the cost of knowing.",
      "Make a choice, and observe how it turns out. It’s all information to base your next decision on, and, if anything, you can get some cool stories.",
      "No regrets!",
      "P.S. I like pide AND gözleme.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  },
  {
    "slug": "fck-around-find-out",
    "title": "F*ck Around & Find Out",
    "subtitle": "Stop researching. Start doing.",
    "date": "January 12, 2024",
    "paragraphs": [
      "When presented with unfamiliar challenges or experiences, there is a common tendency to avoid action until everything feels under control.",
      "An example:",
      "Charlie wants to start making music, so he researches how to do so.",
      "He watches 15 “How To Start Making Music” videos on YouTube, reads Reddit discussions about the best equipment, looks at videos of other people documenting their piano progress over 2 years (and they got really good), and spends a bunch more time filling his mind with information.",
      "Some of this preparation is a good idea, as it gives him a place to start. But after the 2nd “How to Start” video, it becomes a sneaky waste of time. He’s not applying any of this information, so it just becomes noise.",
      "This behavior is likely expressed due to Charlie’s avoidance of making bad music and discomfort with sucking at something.",
      "And so this preparation serves the purpose of gratifying his urge to make music without him confronting any risk or discomfort.",
      "But without risk or discomfort, Charlie doesn’t grow, and can’t play the blues any more than he could before all that preparation.",
      "And the business you have in your head doesn’t exist any more than it did before.",
      "And the person you like still has no clue.",
      "And the book you want to write is still a thought.",
      "And the life you want to live is still a dream.",
      "I would advise the reader not to wait so much before taking actions toward what you find cool. Do, and use information as a tool to adjust and expand. You learn the most through experience.",
      "You want to do something, you don’t know how to do it, and you don’t know what the outcome will be.",
      "Well, sometimes you just gotta fuck around and find out.",
      "https://www.instagram.com/reel/Czf9bKpI758/?igsh=aXE0cjB5enVqZmxy",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  },
  {
    "slug": "feelin-lonesome",
    "title": "Feelin' Lonesome?",
    "subtitle": "On enjoying your own company.",
    "date": "January 5, 2024",
    "paragraphs": [
      "Film: Chungking Express",
      "“If you're lonely when you're alone, you're in bad company.” -Jean-Paul Sartre",
      "A common cycle of distress in many people’s lives is spending time around others (at parties, group hangouts, bars, etc.), feeling unfulfilled or upset with these connections, turning back to isolation, getting sad or bored in our own company, and turning back to socialization.",
      "Usually, the driving emotion behind this cycle is loneliness.",
      "Without the company of others, we feel a mix of sorrow and dullness (called  being lonely), and the natural instinct to combat loneliness is to seek out social situations.",
      "Though social connection is crucial and beautiful, loneliness can often make us desperate and engage in social situations that might not be the best for us, and we end up in the cycle mentioned before.",
      "How can we break out of this cycle, and effectively manage the feeling of loneliness?",
      "Short Answer: Spending more time alone.",
      "Long Answer: The feeling of choosing what happens to us has a huge effect on the human’s mind. Choosing to diet feels way better than having someone else control what we eat. Choosing to read something is more fun than reading whatever you got in English class.",
      "The same applies to isolation.",
      "When we see our time spent alone as something forced on us by the assholery of the world, we tend to feel lonely, and in our mind we’re just waiting for the next time we get to see the homies or live out rom-coms with someone special.",
      "We let isolation give way to feelings of sad boredom.",
      "But if, in our heads, we choose isolation, we can replace these feelings of sad boredom with the gifts offered by being alone: peace, relaxation, and self-exploration.",
      "Kanye cookin' beats, alone.",
      "The greatest remedy to loneliness is actively spending time with yourself. If you have free time and nobody else to spend it with, go take a walk, read a book, drink some coffee, look at the birds, make beats, learn how to code, draw something, go to the thrift store, workout, visit the museum, write about the day, knit, make movies, write raps, or anything cool.",
      "Making this choice to spend time alone feels better than being sad about it. And through these solitary activities, the emotions associated with being alone change from sad boredom to peaceful joy.",
      "Paradoxically, this improves our social connections as well. By enjoying time alone, we gain a sense of inner peace and ability to love life without needing others. This removes any weird clinginess or desire for validation when forming interpersonal connections.",
      "We also gain understanding of ourselves and our interests. By engaging in cool hobbies, adventures, and pondering, we gain complexity within ourselves.",
      "One of the coolest aspects of socializing is exploring the worlds within other people. These worlds are developed quite a bit in solitude.",
      "Spending positive time in solitude can help develop the degree of emotional independence",
      "and personal complexity necessary for healthy, interesting relationships.",
      "And it develops the ability to appreciate life regardless of external situations. Our time is too short to only feel happy within the presence of others.",
      "Be good company for yourself.",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  },
  {
    "slug": "mindradio",
    "title": "MindRadio©",
    "subtitle": "A practice for changing the thoughts playing in your head.",
    "date": "November 10, 2023",
    "paragraphs": [
      "Sometimes the thoughts we have are quite harmful and limiting. The most prevalent reaction to negative thoughts is to try and drive them away.",
      "This is apparent in thinking of “happy places”, watching television, looking at social media, using substances; essentially anything to repress our troubles and feel some respite.",
      "But these are temporary fixes, and reinforce our vulnerability toward any negative feeling.",
      "If we constantly turn to distractions in pleasure or consuming media, then we risk becoming dependent on these outlets whenever encountering difficult emotions/anxieties.",
      "We develop no inner control to rely on in the face of mental chaos, and resort to constantly losing ourselves in distraction rather than navigating the chaos in a productive way.",
      "How can we respond to psychic unrest (AKA bullshit) in a healthier and more beneficial manner?",
      "Most of the harm from negative thoughts comes from how close we feel to them.",
      "The closer we feel, the more we accept whatever notion we have as reality. So when some shitty thought enters your mind, such as “life sucks” or “I’m unlovable”, it automatically feels true. But this is often not the case.",
      "Think of your mind’s thoughts as a radio. It’s this constant system that spits out random ideas based on your experiences in life. Some ideas are accurate and helpful, and some aren't.",
      "When they aren’t, having this image of a radio playing a terrible station can be helpful, because we see our thoughts as separate from ourselves/reality. We can’t turn the radio off, but we can leave it playing in the back of the room while we continue moving forward.",
      "How do we move forward?",
      "One helpful function of unpleasant thoughts is that they can often reveal something that we might want to improve in our lives.",
      "This is where we can use some of the MindRadio©’s information to help us, and dismiss the rest of it.",
      "When encountering any feeling of sadness/worry, ask the question,",
      "“Is there a value of mine that isn’t being met?”",
      "Once answering this question, we can move forward.",
      "I’ll give an example of how this might look in two different situations:",
      "Situation 1",
      "MindRadio©: \"I am fat and ugly and unlovable, I feel terrible after eating four double burgers from Dave’s, fuck.\"",
      "The Self: \"Is there a value of mine that isn’t being met?",
      "I guess I value my health and I’d like to feel a bit more put-together, and recently my choices don’t align with this value.",
      "I can work to make healthier habits and make sure I go to the gym tomorrow. \"",
      "Situation 2",
      "MindRadio©: \"I am fat and ugly and unlovable, everyone at the gym is better than me.\"",
      "The Self: \"Is there a value of mine that isn’t being met?",
      "I value my health and I’d like to feel a bit more put-together. I’m actually taking steps toward this goal by showing up at the gym and cooking nutritious meals at home today. So there’s really nothing to stress about, I’m chillin’.",
      "I’m just gonna continue working out, these thoughts will pass.\"",
      "Situation 1 shows an example where a negative thought can reveal an aspect of life to work on. The person is struggling with health choices, and this leads them to hear thoughts that attack their self-worth and image. After removing the unnecessary and untrue additions of being unlovable and ugly, one is left with a clear direction to move in and improve their way of living (based on what they value).",
      "Situation 2 shows an example where a negative thought is merely a stupid and unhelpful story. The person recognizes the value connected to their negative thoughts of self worth and image, the value of health, and appreciates the fact that they are doing what they can to move in a positive direction. As long as this is the case, there is nothing to truly worry about, and can distance themselves from the negativity.",
      "So we have found a possible framework to navigate mental unrest.",
      "Recognize your thoughts as separate from yourself and from reality; a MindRadio© that continues yapping all the time.",
      "Look for indications that a value of yours isn’t being met.",
      "If it isn’t, try to adjust and move in a direction you care about.",
      "If you’re already doing that, just continue (:",
      "STEP SUMMARY",
      "1) Distance yourself from the MindRadio©",
      "2) Look for a value that isn’t met",
      "3) Move in the direction of your values",
      "Share this post:",
      "Sign up for blog updates!",
      "Join my email list to receive updates and information.",
      "Sign up",
      "Recent Posts",
      "Accept Your Experiences",
      "Apr 24, 2024",
      "How to Practice Antifragility",
      "Apr 24, 2024",
      "Big Dreams, Small Steps",
      "Feb 26, 2024"
    ]
  }
];
