// The early essays — recovered from the first personal site
// (personal-old repo, old-site branch). Edited only for format.

import type { Essay } from "./writing";

export const earlyEssays: Essay[] = [
  {
    "slug": "self-image",
    "title": "Self Image",
    "subtitle": "You can't afford to think small.",
    "date": "July 15, 2025",
    "paragraphs": [
      "You can't afford to think small.",
      "I’m not saying that because it’s cute.",
      "It’s vital that you understand the importance of self-image if you want positive outcomes.",
      "You see, whatever image you have of yourself becomes self-fulfilling.",
      "You act in accordance with the beliefs you hold to be true.",
      "By indulging a negative self-image and keeping your dreams small, you are wasting the machinery and opportunity you have to make a difference and experience beauty.",
      "- “I can’t build a business” → you won’t",
      "- “I fuck up relationships” → you will",
      "- “I’m not an athletic person” → you never will be",
      "Choosing a limiting mental position is an insult to life itself. So tragic.",
      "And you think: “I never chose this. I just am this way.”",
      "Sure, you didn’t sit down and consciously decide to hold yourself back.",
      "These limiting beliefs have built up over the years as a result of certain experiences and how you interpreted them (with or without being aware of it), and they got reinforced the more you acted in alignment with them.",
      "Most of the time, people aren’t even conscious of this process. They just accept whatever enters their mind as truth without evaluating the idea.",
      "Please—take a step back and adopt a more critical eye for your thoughts.",
      "You need to understand that when it comes to “facts” about your personality, this shit isn’t math. It’s not 2 + 2 = 4 every time.",
      "You may have this belief that you’re a shy, quiet person who sits in the back and doesn’t say much. And if you ever feel called to speak your mind, this narrative about your shyness holds you back from doing so.",
      "If you were to let go of this arbitrary barrier you set for yourself, and just said “I’m the type of person who goes first and always speaks their mind,” your behavior would eventually change. (I experienced this exact shift in 10th grade.)",
      "Whatever you believe is the truth about who you are becomes the truth in reality.",
      "Once you become aware of this fact—that the story you have about yourself is your choice—",
      "the question no longer becomes, “Is this true?” but rather, “Does this serve me?”",
      "If you’re not actively working to cultivate a strong conviction—if you’re not listening to lectures or reading books or talking to people that expand your mind and the scope of ambition, that bolster a sense of strength and capability and resilience—",
      "then you are choosing to stay small.",
      "This isn’t just about you feeling good or bad about yourself.",
      "Adopting a negative self-image is ethically and morally wrong.",
      "You have the ability to create so much joy, happiness, progress, change, and greatness. You can be a source of strength for your friends, family, and community. You can be in wonderful health and be a source of abundance in the world—",
      "and you’re choosing to believe otherwise.",
      "The fuck is that?",
      "It’s an uncomfortable shift. You’re attached to your wonderful limitations. They keep you safe and in your familiar mediocrity.",
      "But my guess is you don’t wanna stay there.",
      "You gotta start the shift.",
      "Push the edges. Clear out the self-pity and sob stories and the struggle olympics.",
      "Stop telling yourself depressing, lame shit—and stop listening to it.",
      "Imagine who you want to be. Write it down. Find people who have the same message.",
      "And drill all that shit into your brain with relentless force.",
      "Who you are, what you’re meant for—that’s a story you tell yourself.",
      "Choose a story that feels grand, beautiful, and whatever else you want it to be.",
      "You’ll never run out of ways to grow or serve.",
      "You will never exhaust your potential in this lifetime.",
      "So think bigger.",
      "---",
      "PS: Practices I Use",
      "- I read my “vision” document every morning, which describes the life and characteristics I’m working toward from the perspective of my 22-year-old self—who already has it. Write what you want with no fear, and read that shit.",
      "- I listen to tapes when I’m walking, driving, lifting—recordings that hammer in ideas and attitudes conducive to wealth, strength, and ambition. We pick up our self-concept from what we’re told, taught, or see. In the digital age, you can choose who and what you listen to. Get into physical and digital spaces with optimism and big goals.",
      "- Fill your mind with movies, books, music, and images that make you feel good, excited, aligned. Save all your favorite things somewhere easily accessible, and keep a clear conduit between your attention and what you love.",
      "- Ruthlessly avoid and eliminate sources of negativity and distraction in your life."
    ]
  },
  {
    "slug": "nyu",
    "title": "NYU Essay",
    "subtitle": "The essay that took me to NYC.",
    "date": "March 1, 2025",
    "paragraphs": [
      "It was a college calligraphy class that distinguished Apple from the rest of Silicon Valley. The seemingly useless knowledge of typography kindled Steve Jobs’ love for design, ultimately producing the wondrous interface with which I develop websites, design clothes, and write these words.",
      "As Jobs put it: “Technology alone is not enough. It’s technology married with the liberal arts, married with the humanities, that yields the results that make our hearts sing.”",
      "Since hearing that story at 13, it’s become my professional mission to build tools that aren’t just utilitarian but serve as art in their own right—works that make hearts sing.",
      "This pursuit led me to Combat, a clothing company I built with my best friend. What began as a side project quickly became a platform for exploring how design, branding, and storytelling can empower people. We taught ourselves graphic design, built an online presence, and grew a simple idea to $30,000 in revenue.",
      "As Combat grew, I became fascinated by how digital touchpoints shape perception and transform ideas into movements. I realized ideas resonate not just in content but in experience. The change I seek to make lies at that intersection of technology and storytelling.",
      "At my current school, this blend is hard to come by, so I cultivate it myself. I love the pressure of waking up at 3 a.m. to produce videos, freelance, and design before class, but this sharp division between technical study and creative ambition has led me to realize I need an institution that integrates both.",
      "That’s why I’m drawn to NYU.",
      "At the College of Arts & Science, I hope to pair rigorous technical training in CS with psychology and media studies, exploring courses like UX Design and Cognition and Perception. This curriculum would sharpen my ability to craft human-centered experiences—understanding not just how a product is created, but why, for whom, and with what impact.",
      "Beyond the classroom, I plan to immerse myself in NYU’s dynamic ecosystem—building at the Leslie eLab and Tech@NYU, brainstorming with founders at StartupNYU, and drawing inspiration from Tisch ITP’s artists. These experiences will directly shape my work as I collaborate with NYC’s startups and fashion industry.",
      "I want an institution where I can work to bridge beauty with functionality, where ambition and creativity aren’t just encouraged, but expected. At NYU, in a city that thrives on creative hustle, these connections wouldn’t be an uphill battle—they’d be inevitable."
    ]
  },
  {
    "slug": "depth",
    "title": "Art & The Network",
    "subtitle": "The importance of depth in a digital age.",
    "date": "January 25, 2025",
    "paragraphs": [
      "It’s never been this easy. \nYou can make something right now, press a button, and have a million eyes on your work without leaving the house.\nThis is great. I think it’s way better than what we used to have, the external barriers have broken down and we have way more room for creativity and discovery.",
      "We used to have so many barriers about where you lived, who you knew, going through institutions and those who already had power.\nAnd you could only find art if you were lucky. Museum nearby, artists live close, etc. \nNow you don’t need to ask permission, and you can see 100 new artworks in 30 minutes on Instagram.",
      "But people who love art need to be mindful. This new shift can create more opportunity for beauty and meaning to be shared, for people to make a living doing what they love, but it can also rob the juice of what makes art worthwhile.",
      "The shift toward accessibility and opportunity is powered heavily by social networks. Many have found their audiences and their people through sharing on these spaces. It’s a wonderful thing.",
      "The issue arises when you consider the nature of how you experience things on social platforms. It is not a good place on shortform to spend time experiencing art or creating things with Instagram being their final exhibition room. It is a good place to discover and form connections, but not for an artist to make the central goal for their art nor for the audience to make instagram their museum. It’s too short.",
      "It’s like speed dating vs. finding actual love.",
      "I’d argue that this world of short marketing bits and 60 second stories doesn’t sufficiently fill the role of longer, deeper pieces. It’s more of a place of discovery, not nourishment. Staying solely in this shallow ecosystem, both as the artist and the audience is not ideal.",
      "For the actual artist, it means that you create things on very shortened timelines and depth. Whereas I had dreams of creating films and writing books, as a result of the immediate market I saw, I shifted toward writing 60 second scripts and making videos that truly, in my eyes, offered no novel perspective or insights or even beauty, but my focus subconscious shifted toward creating something that would switch cuts and have trending audio rather than creating something that really said something. What happened within the span of a day was not much. Whereas beautiful stories unravel over weeks, years. Let ideas, let stories develop, rather than rushing it all.",
      "For audiences, this translates into consuming fragmented bursts of information that rarely stick. Long-form content like books, films, and deep projects offers transformative experiences, but these are increasingly overshadowed by ephemeral reels and posts. You press a like button, but you don’t get to love it the way you love a movie, or a painting. It’s why people go to the Louvre to see the Mona Lisa instead of looking at a picture of it on Google. You rarely hear people pointing to specific TikToks and saying it changed their life. It may be the accumulation of that person’s work, but the effect of a single piece usually gets drowned out by everything else you see in that 45 minute block of scrolling. On the other hand, reading a life-changing book, a film, a lecture, because these pieces go deeper and we have more time to digest them. Most of the time you don’t binge 100 books back to back, or 100 movies. But 100 instagram reels, that’s like 40 minutes. Some may be interesting, educational even, but they don’t stick.",
      "On the contrary, often it feels as though one’s been robbed of their time by short things. Why? Because the shortness of it, followed by another, and another, simply jerks your mind into ephemeral moments of excitement, a one-hit version of the awe that you experience with a work of art, then quickly covers up the last with another.\nThis is why even the best short pieces feel unsatisfactory.",
      "So I think if the importance of the social network gains too much weight in the artists or the audience’s mind, If social media is the primary place where you “experience art” both in terms of sharing and seeing it, it creates a very shallow form of existence. \nThe artist constantly feels the need to “put something out”, and the audience constantly, often mindlessly, “consumes” the content.\nAnd in day to day life, it means you operate on a very shallow field of existence. Your thoughts are elementary, you are jerked by little stimuli and jokes and reels, as opposed to contemplating complex, meaningful ideas from the books you read, or spending a lot of time coming up with projects to work on that are truly ambitious.\nThis shallow mode of operation permeates life itself. Constant exposure to surface-level stimuli dulls our capacity for deep thought and meaningful action. Instead of pursuing ambitious, complex projects, we’re caught in a loop of elementary ideas and fleeting distractions. Yet, the greatest achievements demand time, focus, and a willingness to go deeper than others dare to.\nBecause the greatest feats take time. You discover unknown treasures by going deeper than anyone else dares to go.\nAnd at this point in time, that number is few.\nThis is why you don’t see people pointing to a TikTok and saying it changed their life. What’s your favorite TikTok? What’s your favorite Instagram post?\nYouTube videos are more likely because they are longer generally.\nBut a book, a lecture, a movie, an exhibition, these things offer transformative experiences. Because there is intimacy, time spent, focus, no other reels next to it distracting you. And they go into more depth.",
      "That is what we need. We need more of those experiences where you feel the world expand, you feel not alone, you see a new way forward. But you don’t really get those experiences on Instagram. You only find the people who may offer it to you, but it’s not the space to soak in the work.",
      "Notice that the prescription doesn’t require you to leave the internet or cut out all “shallow” endeavors, as visibility is a key part of creating a working, successful project. But it needs to help the real work succeed, rather than steal critical energy from it, focusing on making a good post instead of good work.",
      "The spaces should be used as a tool to find the people for your art, not the final exhibition. The goal should not be likes and engagements, but to create a meaningful contribution and find the people who’d love it.",
      "But if 30seconds of you piques their interest, and they wish to explore, and all you have are other 30 second videos, all you have done is amused them for a bit. The only true value of these things are to bridge a stranger to an audience to a true supporter of the deep works you’ve produced.",
      "I’m not arguing that these networks are bad, or that content is inherently stupid, or that these places should be abandoned. I think this development in our world is a marvelous increase in connectivity in the way telephones and railroads and airplanes changed things. All I’m pointing out is that in order to reap the true benefits, to preserve the function and beauty of art/creativity as the producer and the enjoyer, to be mindful of these influences, and not to sacrifice too much depth for visibility.",
      "There need to be these greater, deeper works at your foundation as an artist or entrepreneur or worker that an audience can explore and be enriched by.\nThis is where the fruits of creative labor (in the form of money and fulfillment) are found.\nAnd to do that, you need this mode of long-term, focused, committed thinking and work.\nSo how do you cultivate depth in this current state of affairs?",
      "- Carve Out Deep Work Time: Dedicate continuous, uninterrupted sessions to meaningful work or practice. These hours, free from distractions, are where breakthroughs happen.",
      "- Create Strong Constraints: Limit engagement with shallow, peripheral activities like social media, emails, and notifications. Set clear boundaries on when and how long you interact with these platforms.",
      "- Pursue Long-Term Projects: Channel your core efforts into deep, unique endeavors. Whether it’s writing a book, developing a design project, or launching an entrepreneurial venture, these projects will have the greatest impact on the world—and on your own fulfillment.",
      "The artist must treat long work, solitary time, and silence as sacred. Though these short bursts of engagement, these efforts of marketing and daily posts and quick nuggets of art can be momentarily exciting, commercially rewarding, and a place of discovery,\nIt all goes to naught without the deep, concentrated work that the artist creates for the world.",
      "It is the artist’s duty to preserve this space and depth.\nBoth for the artist and the enjoyer. \nAnd as an enthusiastic audience, you must go deeper as well. Do not rely on algorithms and give 30 seconds each to 1000 people. The connection, depth, enrichment we seek is found through dedicating time and focus toward the art that speaks most to our soul. \nWe must create deeper, meaningful, longer works so that we can be truly transformed rather than distracted or amused."
    ]
  },
  {
    "slug": "brother",
    "title": "Letter to Abdul",
    "subtitle": "The letter I wrote my best friend as he moved to New York.",
    "date": "August 8, 2024",
    "paragraphs": [
      "My Dear Friend,",
      "I have more to say than time or paper to do so, but I'll try to cover some of it.",
      "When I was younger, I became very interested in deep grandiose philosophical questions and would spend a lot of time thinking of answers.",
      "One of these questions was \"what makes a great friend?\"",
      "I came up with a nice and dandy answer, that being someone who you can be vulnerable around and who pushes you to grow. Someone who is there for you, wishing for your wellbeing as much as his own, and who brings you closer to the person you want to be.",
      "Sweet, now I know.",
      "But there's a vital difference between knowing something in your head and actually understanding it. And in that regard, I'd like to thank you.",
      "Through our years together, I've come to truly know \nwhat it means to have a great friend.",
      "If you were to turn the happiest and most beautiful moments of my life into a film reel, you'd show up thousands of times.",
      "Our first trip to New York, where we climbed the Williamsburg Bridge and enjoyed Good Mood Food.",
      "Helping your father with Harevestrolley and exploring Chicago together.",
      "All the romantic dates we should've asked girls on but instead experienced together:\nIkea, walking in Naperville, exploring Evanston, eating Mama Maria’s at the Prairie Center, watching 500 Days of Summer, drawing the Chicago skyline, scouting for ass at Lake Geneva, to name a few.",
      "And just recently, our first road trip through half of America. The music, biking, talking, I enjoyed every second. That was the most fun I've ever had. \nExcept for meeting Meano.  Fucking dick.",
      "But it's not just the picturesque memories I cherish with you.\nHaving you as company turned ordinary, dull, difficult times into beautiful stories as well.\nWhen we fucked up your wall with the ping pong table, we struggled for a place to sleep in New York, we worked out in my basement, we ran 13 miles, we ruined our \nromantic relations, sharing these struggles with you made them adventurous and exciting.",
      "Thank you for amplifying the good times and transforming the hard times into cool stories. \nYou've always helped me feel more alive.",
      "You've also been my biggest rival.",
      "Normally you want to be great and you want your rival to be weak so you beat him.\nBut since my rival is also my best friend, and I only want the world for you, my only option is to always try and run a little faster than you, work a little harder, and if I can't, I MUST AT LEAST keep up.",
      "When I'm tired, I know you're in the gym and I gotta keep up. \nWhen I'm uninspired, I know you're still creating and I gotta keep up.\nWhen I'm doubting myself, I know you're still moving and I gotta keep up. \nAnd I gotta win.",
      "I don't try to beat you because I want you to lose. I try to beat you because that push for growth feels amazing, it feels like I am living the way I was meant to, and YOU SPARK THAT FIRE. I believe I do the same for you when I'm on my shit, and I love that image of 2 kids trying to run faster than each other and, in the end, being faster than everyone else who doesn't have a friend to push them.",
      "Thank you for adding that gas to the flame.",
      "And thank you for the chance to use the words \"my best friend\" when talking to others.\nMy best friend and I did a podcast last weekend.\nNext summer, I intend to ride motorbikes in Istanbul with my best friend.\nI gotta lock the fuck in so I can afford New York rent with my best friend after college.\nShit like that.",
      "You’ve given me a lot.\nYou've given me thicker skin by flaming the shit out of me.\nYou've given me space to talk about what I love.\nYou've accepted all the different parts of myself.\nYou've pushed me to think less and do more.\nYou've shown me so much cool shit.\nYou've expanded my lust for life and adventure.\nYou've shifted my view of difficulty into a beautiful challenge.\nYou've helped me see the strengths and power I have within me.\nYou've given me the ability to believe in my dreams. And in myself.",
      "I now actually believe that I can make my dreams a reality. Which kind of fucking sucks, because now I always feel like I HAVE TO TRY. \nThanks for that headache.",
      "I know I'd rather live with chasing a dream than without, and you're a big reason why I'm saying that.",
      "So, I'm making a written promise right here right now that I'm going to work toward building my dreams until the day I die, never to let bullshit or fear or busywork or impostor syndrome or other people extinguish that fire.",
      "I'm getting fucking shredded. Completely mogging you.\nI'm becoming a baller. When we go to the restaurant I'm paying for ALL THE HOMIES.\nI'm going to make beautiful shit and give it to the world.",
      "Creative Soldier and Ali Amant the next Yeezus and Hova, once we make it to New York?\nIt's OVER!\nI'm going to find my way to New York City. We're getting that apartment. It's gonna be the nicest fucking apartment in the world.\nChicks are gonna love it.\nWe're getting beautiful girls and going on double dates. \nWe're going to live out the dream or die trying.",
      "But you gotta hold up your end of the bargain. Beat the shit out of New York bro, own it.",
      "Make the coolest shit you've ever made. Don't skip days. \nMake smart decisions between adventure and focused building. \nConnect the dots looking backward. Trust in the ways of Allah. Don't lose faith.\nDon't let fear or confusion stop you. It's great if you don't have everything figured out. You're finding your way.\nNever lose that childish spirit, that hunger for experience. \nDon't let anything fuck up your vision.",
      "You're gonna make it. And when you make it, keep that same perspective.",
      "I believe in you, Abdul. You'll make it. Even if you don't know what that means yet.",
      "You have the desire. You have what it takes inside of you.",
      "Now it's just a matter of digging that up, sculpting it day by day through consistent effort.\nAs long as you're trying, you're on the right path.",
      "And while you're building this beautiful life and vision in reality, remember to look around and appreciate the beauty around you.",
      "It's always right now. Doesn't matter what happened before, and the future isn't promised.",
      "Everything is right now.",
      "Appreciate your moment.",
      "Listen to your heart.",
      "Keep going.",
      "Don't stop.",
      "I'll join you in NY soon."
    ]
  }
];
